language: python

addons:
  firefox: latest

python:
    - "2.7.12"

services:
    - postgresql

before_install:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver-v0.19.1-linux64.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver

install:
    - pip install -r requirements.txt

before_script:
  - psql -c "CREATE ROLE osschallenge CREATEDB LOGIN PASSWORD 'osschallenge';" -U postgres
  - psql -c "CREATE DATABASE osschallenge;" -U postgres

script: coverage run manage.py test osschallenge
