language: python

python:
    - "2.7.12"

services:
    - postgresql

install:
    - pip install -r requirements.txt

before_script:
  - psql -c 'create database osschallenge;' -U postgres

script: coverage run manage.py test osschallenge


