language: python

addons:
    chrome: stable

python:
    - "2.7.12"

services:
    - postgresql

before_install:
    - wget https://pypi.python.org/packages/c6/af/e95a492e882f2618e376ea3eee283d774265288fea4185fbe933879811e7/chrome-driver-2.26.0.1.tar.gz
    - mkdir chromedriver
    - tar -xzf chrome-driver-2.26.0.1.tar.gz -C chromedriver
    - export PATH=$PATH:/usr/lib/chromium-browser/

install:
    - pip install -r requirements.txt

before_script:
    - psql -c "CREATE ROLE osschallenge CREATEDB LOGIN PASSWORD 'osschallenge';" -U postgres
    - psql -c "CREATE DATABASE osschallenge;" -U postgres

script: coverage run manage.py test osschallenge
