language: python

addons:
    chrome: stable

python:
    - "2.7.12"

services:
    - postgresql

before_install:
    - wget https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip
    - sudo apt-get install unzip
    - unzip chromedriver_linux64.zip -d /usr/lib/chromium-browser/
    - chmod +x chromedriver
    - export PATH=$PATH:/usr/lib/chromium-browser/

install:
    - pip install -r requirements.txt

before_script:
    - psql -c "CREATE ROLE osschallenge CREATEDB LOGIN PASSWORD 'osschallenge';" -U postgres
    - psql -c "CREATE DATABASE osschallenge;" -U postgres

script: coverage run manage.py test osschallenge
