version: "3"
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=oss_challenge
      - POSTGRES_USER=osschallenge
      - POSTGRES_PASSWORD=osschallenge

  phppgadmin:
    image: zhajor/docker-phppgadmin
    depends_on:
      - postgres
    links:
      - postgres
    ports:
        - "8080:80"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432

  osschallenge:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - data:/data

volumes:
  data:
